### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by jfordnose64** [jfordnose64/assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary
- [x] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [x] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [x] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by jfordnose64** [comment]
[jackson's Resume (1).pdf](https://github.com/jfordnose64/assignments/files/3647418/jackson.s.Resume.1.pdf)

**Comment by ktrammell95** [comment]
Very nice format, you still have a lot of white space so I would see about using up some if you can
![Screen Shot 2019-09-26 at 3 46 10 PM](https://user-images.githubusercontent.com/10440779/65719919-dcfe6b00-e074-11e9-90af-82fa50fa34bb.png)

Think about moving your projects up above experience and adding a couple more if you can. You are moving into tech and want to show off your work. It's ok to use homework assignments that you are proud of or really challenged you.
